# Generated by Django 5.1.6 on 2025-02-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario del Sistema', 'verbose_name_plural': 'Usuarios del Sistema'},
        ),
    ]
