# Generated by Django 5.1.6 on 2025-02-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255, verbose_name='Acción')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acción')),
                ('ip_usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP del Usuario')),
                ('objeto_afectado', models.TextField(blank=True, null=True, verbose_name='Objeto Afectado')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcciones',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_accion', models.DateTimeField()),
                ('ip_usuario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'registro_acciones',
                'db_table_comment': 'Esta tabla almacena un historial de las acciones realizadas por los usuarios, como accesos y cambios importantes.',
            },
        ),
    ]
